
spring.application.name=social-cup-backend

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

stripe.secret-key=${STRIPE_SECRET_KEY}
stripe.price-id=${STRIPE_PRICE_ID}
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET:}
