CREATE TABLE neighbourhoods (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                name VARCHAR(100) NOT NULL UNIQUE,
                                active BOOLEAN NOT NULL DEFAULT TRUE,
                                sort_order INTEGER NOT NULL DEFAULT 0,
                                created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);