CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    display_name VARCHAR(100) NOT NULL,
    profile_photo_path VARCHAR(500),
    home_neighbourhood_id BIGINT,
    email_verified_at TIMESTAMPTZ,
    onboarding_completed_at TIMESTAMPTZ,
    account_status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_users_home_neighbourhood
        FOREIGN KEY (home_neighbourhood_id) REFERENCES neighbourhoods (id)
);

CREATE INDEX idx_users_home_neighbourhood_id
    ON users (home_neighbourhood_id);

CREATE INDEX idx_users_account_status
    ON users (account_status);

CREATE TABLE auth_identities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider VARCHAR(20) NOT NULL,
    provider_user_id VARCHAR(255),
    password_hash VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_auth_identities_user_provider
        UNIQUE (user_id, provider),
    CONSTRAINT fk_auth_identities_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT chk_auth_identities_provider
        CHECK (provider IN ('EMAIL', 'GOOGLE', 'APPLE')),
    CONSTRAINT chk_auth_identities_credentials
        CHECK (
            (provider = 'EMAIL' AND password_hash IS NOT NULL)
            OR
            (provider IN ('GOOGLE', 'APPLE') AND provider_user_id IS NOT NULL)
        )
);

CREATE INDEX idx_auth_identities_user_id
    ON auth_identities (user_id);

CREATE UNIQUE INDEX uq_auth_identities_provider_user_id
    ON auth_identities (provider, provider_user_id)
    WHERE provider_user_id IS NOT NULL;

CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_refresh_tokens_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT chk_refresh_tokens_expiry
        CHECK (expires_at > created_at),
    CONSTRAINT chk_refresh_tokens_revocation
        CHECK (revoked_at IS NULL OR revoked_at >= created_at)
);

CREATE INDEX idx_refresh_tokens_user_id
    ON refresh_tokens (user_id);

CREATE INDEX idx_refresh_tokens_expires_at
    ON refresh_tokens (expires_at);

CREATE TABLE email_verification_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_email_verification_tokens_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT chk_email_verification_tokens_expiry
        CHECK (expires_at > created_at),
    CONSTRAINT chk_email_verification_tokens_consumed
        CHECK (consumed_at IS NULL OR consumed_at >= created_at)
);

CREATE INDEX idx_email_verification_tokens_user_id
    ON email_verification_tokens (user_id);

CREATE INDEX idx_email_verification_tokens_expires_at
    ON email_verification_tokens (expires_at);

CREATE TABLE password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_password_reset_tokens_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT chk_password_reset_tokens_expiry
        CHECK (expires_at > created_at),
    CONSTRAINT chk_password_reset_tokens_consumed
        CHECK (consumed_at IS NULL OR consumed_at >= created_at)
);

CREATE INDEX idx_password_reset_tokens_user_id
    ON password_reset_tokens (user_id);

CREATE INDEX idx_password_reset_tokens_expires_at
    ON password_reset_tokens (expires_at);

CREATE TABLE coffee_preferences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    display_name VARCHAR(100) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX idx_coffee_preferences_active
    ON coffee_preferences (active);

CREATE TABLE user_coffee_preferences (
    user_id BIGINT NOT NULL,
    coffee_preference_id BIGINT NOT NULL,
    CONSTRAINT pk_user_coffee_preferences
        PRIMARY KEY (user_id, coffee_preference_id),
    CONSTRAINT fk_user_coffee_preferences_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_user_coffee_preferences_preference
        FOREIGN KEY (coffee_preference_id) REFERENCES coffee_preferences (id)
);

CREATE INDEX idx_user_coffee_preferences_preference_id
    ON user_coffee_preferences (coffee_preference_id);
