CREATE TABLE cafes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(500) NOT NULL,
    neighbourhood_id BIGINT NOT NULL,
    latitude NUMERIC(9, 6),
    longitude NUMERIC(9, 6),
    perk_line VARCHAR(500),
    payout_rate_per_credit NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    featured BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    scan_slug VARCHAR(255) NOT NULL UNIQUE,
    pin_hash VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cafes_neighbourhood
        FOREIGN KEY (neighbourhood_id) REFERENCES neighbourhoods (id),
    CONSTRAINT chk_cafes_latitude
        CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
    CONSTRAINT chk_cafes_longitude
        CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180),
    CONSTRAINT chk_cafes_payout_rate_per_credit
        CHECK (payout_rate_per_credit >= 0)
);

CREATE INDEX idx_cafes_neighbourhood_id
    ON cafes (neighbourhood_id);

CREATE INDEX idx_cafes_active_featured
    ON cafes (active, featured);

CREATE TABLE cafe_photos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cafe_id BIGINT NOT NULL,
    storage_path VARCHAR(500) NOT NULL,
    display_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cafe_photos_cafe
        FOREIGN KEY (cafe_id) REFERENCES cafes (id),
    CONSTRAINT chk_cafe_photos_display_order
        CHECK (display_order >= 0)
);

CREATE INDEX idx_cafe_photos_cafe_id_display_order
    ON cafe_photos (cafe_id, display_order);

CREATE TABLE cafe_opening_hours (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cafe_id BIGINT NOT NULL,
    day_of_week SMALLINT NOT NULL,
    opens_at TIME,
    closes_at TIME,
    closed BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_cafe_opening_hours_cafe_day
        UNIQUE (cafe_id, day_of_week),
    CONSTRAINT fk_cafe_opening_hours_cafe
        FOREIGN KEY (cafe_id) REFERENCES cafes (id),
    CONSTRAINT chk_cafe_opening_hours_day_of_week
        CHECK (day_of_week BETWEEN 1 AND 7),
    CONSTRAINT chk_cafe_opening_hours_times
        CHECK (
            (closed = TRUE AND opens_at IS NULL AND closes_at IS NULL)
            OR
            (closed = FALSE AND opens_at IS NOT NULL AND closes_at IS NOT NULL)
        )
);

CREATE TABLE vibe_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    display_name VARCHAR(100) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX idx_vibe_tags_active
    ON vibe_tags (active);

CREATE TABLE cafe_vibe_tags (
    cafe_id BIGINT NOT NULL,
    vibe_tag_id BIGINT NOT NULL,
    CONSTRAINT pk_cafe_vibe_tags
        PRIMARY KEY (cafe_id, vibe_tag_id),
    CONSTRAINT fk_cafe_vibe_tags_cafe
        FOREIGN KEY (cafe_id) REFERENCES cafes (id),
    CONSTRAINT fk_cafe_vibe_tags_vibe_tag
        FOREIGN KEY (vibe_tag_id) REFERENCES vibe_tags (id)
);

CREATE INDEX idx_cafe_vibe_tags_vibe_tag_id
    ON cafe_vibe_tags (vibe_tag_id);

CREATE TABLE cafe_devices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cafe_id BIGINT NOT NULL,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_used_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    CONSTRAINT fk_cafe_devices_cafe
        FOREIGN KEY (cafe_id) REFERENCES cafes (id),
    CONSTRAINT chk_cafe_devices_last_used
        CHECK (last_used_at IS NULL OR last_used_at >= created_at),
    CONSTRAINT chk_cafe_devices_revocation
        CHECK (revoked_at IS NULL OR revoked_at >= created_at)
);

CREATE INDEX idx_cafe_devices_cafe_id
    ON cafe_devices (cafe_id);

CREATE TABLE drinks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cafe_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(30) NOT NULL,
    description TEXT,
    photo_path VARCHAR(500),
    retail_price NUMERIC(10, 2) NOT NULL,
    credit_price INTEGER NOT NULL,
    signature BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_drinks_cafe
        FOREIGN KEY (cafe_id) REFERENCES cafes (id),
    CONSTRAINT chk_drinks_type
        CHECK (type IN ('MATCHA', 'ESPRESSO', 'COLD_BREW', 'LATTE')),
    CONSTRAINT chk_drinks_retail_price
        CHECK (retail_price >= 0),
    CONSTRAINT chk_drinks_credit_price
        CHECK (credit_price > 0)
);

CREATE INDEX idx_drinks_cafe_id_active
    ON drinks (cafe_id, active);

CREATE INDEX idx_drinks_type
    ON drinks (type);

CREATE INDEX idx_drinks_signature
    ON drinks (signature)
    WHERE signature = TRUE AND active = TRUE;
