CREATE TABLE drink_ratings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    drink_id BIGINT NOT NULL,
    stars INTEGER NOT NULL,
    note VARCHAR(140),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_drink_ratings_user_drink
        UNIQUE (user_id, drink_id),
    CONSTRAINT fk_drink_ratings_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_drink_ratings_drink
        FOREIGN KEY (drink_id) REFERENCES drinks (id),
    CONSTRAINT chk_drink_ratings_stars
        CHECK (stars BETWEEN 1 AND 5)
);

CREATE INDEX idx_drink_ratings_drink_id
    ON drink_ratings (drink_id);

CREATE INDEX idx_drink_ratings_created_at
    ON drink_ratings (created_at);
