CREATE TABLE subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    stripe_customer_id VARCHAR(255),
    stripe_subscription_id VARCHAR(255) UNIQUE,
    status VARCHAR(30) NOT NULL,
    current_period_start TIMESTAMPTZ,
    current_period_end TIMESTAMPTZ,
    cancel_at_period_end BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_subscriptions_user_id UNIQUE (user_id),
    CONSTRAINT fk_subscriptions_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT chk_subscriptions_period
        CHECK (
            current_period_start IS NULL
            OR current_period_end IS NULL
            OR current_period_end > current_period_start
        )
);

CREATE INDEX idx_subscriptions_status
    ON subscriptions (status);

CREATE INDEX idx_subscriptions_stripe_customer_id
    ON subscriptions (stripe_customer_id);

CREATE TABLE billing_cycles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id BIGINT NOT NULL,
    period_start TIMESTAMPTZ NOT NULL,
    period_end TIMESTAMPTZ NOT NULL,
    stripe_reference VARCHAR(255) UNIQUE,
    status VARCHAR(30) NOT NULL,
    processed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_billing_cycles_subscription
        FOREIGN KEY (subscription_id) REFERENCES subscriptions (id),
    CONSTRAINT chk_billing_cycles_period
        CHECK (period_end > period_start)
);

CREATE INDEX idx_billing_cycles_subscription_id
    ON billing_cycles (subscription_id);

CREATE INDEX idx_billing_cycles_status
    ON billing_cycles (status);

CREATE TABLE stripe_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stripe_event_id VARCHAR(255) NOT NULL UNIQUE,
    event_type VARCHAR(100) NOT NULL,
    processed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_stripe_events_event_type
    ON stripe_events (event_type);

CREATE INDEX idx_stripe_events_processed_at
    ON stripe_events (processed_at);

CREATE TABLE credit_accounts (
    user_id BIGINT PRIMARY KEY,
    credits_remaining INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_credit_accounts_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT chk_credit_accounts_nonnegative_balance
        CHECK (credits_remaining >= 0)
);

CREATE TABLE credit_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    billing_cycle_id BIGINT,
    redemption_id BIGINT,
    type VARCHAR(30) NOT NULL,
    amount INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_credit_transactions_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_credit_transactions_billing_cycle
        FOREIGN KEY (billing_cycle_id) REFERENCES billing_cycles (id),
    CONSTRAINT chk_credit_transactions_type
        CHECK (type IN ('CYCLE_GRANT', 'CYCLE_EXPIRY', 'REDEMPTION', 'VOID_REFUND')),
    CONSTRAINT chk_credit_transactions_nonzero_amount
        CHECK (amount <> 0)
);

CREATE INDEX idx_credit_transactions_user_id
    ON credit_transactions (user_id);

CREATE INDEX idx_credit_transactions_billing_cycle_id
    ON credit_transactions (billing_cycle_id);

CREATE INDEX idx_credit_transactions_redemption_id
    ON credit_transactions (redemption_id);

CREATE INDEX idx_credit_transactions_type
    ON credit_transactions (type);

CREATE INDEX idx_credit_transactions_created_at
    ON credit_transactions (created_at);
