CREATE TABLE redemption_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    cafe_id BIGINT NOT NULL,
    drink_id BIGINT NOT NULL,
    credit_cost INTEGER NOT NULL,
    qr_token_hash VARCHAR(255) NOT NULL UNIQUE,
    backup_code_hash VARCHAR(255) NOT NULL UNIQUE,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    cancelled_at TIMESTAMPTZ,
    consumed_at TIMESTAMPTZ,
    CONSTRAINT fk_redemption_sessions_member
        FOREIGN KEY (member_id) REFERENCES users (id),
    CONSTRAINT fk_redemption_sessions_cafe
        FOREIGN KEY (cafe_id) REFERENCES cafes (id),
    CONSTRAINT fk_redemption_sessions_drink
        FOREIGN KEY (drink_id) REFERENCES drinks (id),
    CONSTRAINT chk_redemption_sessions_credit_cost
        CHECK (credit_cost > 0),
    CONSTRAINT chk_redemption_sessions_status
        CHECK (status IN ('ACTIVE', 'CANCELLED', 'EXPIRED', 'REDEEMED')),
    CONSTRAINT chk_redemption_sessions_expiry
        CHECK (expires_at > created_at)
);

CREATE INDEX idx_redemption_sessions_member_id
    ON redemption_sessions (member_id);

CREATE INDEX idx_redemption_sessions_cafe_id
    ON redemption_sessions (cafe_id);

CREATE INDEX idx_redemption_sessions_drink_id
    ON redemption_sessions (drink_id);

CREATE INDEX idx_redemption_sessions_status_expires_at
    ON redemption_sessions (status, expires_at);

CREATE TABLE redemptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL UNIQUE,
    member_id BIGINT NOT NULL,
    cafe_id BIGINT NOT NULL,
    drink_id BIGINT NOT NULL,
    credits_spent INTEGER NOT NULL,
    credit_value_snapshot NUMERIC(10,2) NOT NULL,
    member_value NUMERIC(10,2) NOT NULL,
    payout_rate_snapshot NUMERIC(10,2) NOT NULL,
    payout_amount NUMERIC(10,2) NOT NULL,
    margin NUMERIC(10,2) NOT NULL,
    status VARCHAR(30) NOT NULL,
    redeemed_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_redemptions_session
        FOREIGN KEY (session_id) REFERENCES redemption_sessions (id),
    CONSTRAINT fk_redemptions_member
        FOREIGN KEY (member_id) REFERENCES users (id),
    CONSTRAINT fk_redemptions_cafe
        FOREIGN KEY (cafe_id) REFERENCES cafes (id),
    CONSTRAINT fk_redemptions_drink
        FOREIGN KEY (drink_id) REFERENCES drinks (id),
    CONSTRAINT chk_redemptions_credits_spent
        CHECK (credits_spent > 0),
    CONSTRAINT chk_redemptions_credit_value_snapshot
        CHECK (credit_value_snapshot >= 0),
    CONSTRAINT chk_redemptions_member_value
        CHECK (member_value >= 0),
    CONSTRAINT chk_redemptions_payout_rate_snapshot
        CHECK (payout_rate_snapshot >= 0),
    CONSTRAINT chk_redemptions_payout_amount
        CHECK (payout_amount >= 0)
);

CREATE INDEX idx_redemptions_member_id
    ON redemptions (member_id);

CREATE INDEX idx_redemptions_cafe_id
    ON redemptions (cafe_id);

CREATE INDEX idx_redemptions_drink_id
    ON redemptions (drink_id);

CREATE INDEX idx_redemptions_status
    ON redemptions (status);

CREATE INDEX idx_redemptions_redeemed_at
    ON redemptions (redeemed_at);

CREATE TABLE redemption_voids (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    redemption_id BIGINT NOT NULL UNIQUE,
    admin_user_id BIGINT NOT NULL,
    reason VARCHAR(500) NOT NULL,
    voided_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_redemption_voids_redemption
        FOREIGN KEY (redemption_id) REFERENCES redemptions (id),
    CONSTRAINT fk_redemption_voids_admin_user
        FOREIGN KEY (admin_user_id) REFERENCES users (id)
);

CREATE INDEX idx_redemption_voids_admin_user_id
    ON redemption_voids (admin_user_id);

ALTER TABLE credit_transactions
    ADD CONSTRAINT fk_credit_transactions_redemption
    FOREIGN KEY (redemption_id) REFERENCES redemptions (id);
