CREATE TABLE platform_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key VARCHAR(100) NOT NULL UNIQUE,
    setting_value VARCHAR(500) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE payout_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    status VARCHAR(30) NOT NULL,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_payout_runs_created_by
        FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT chk_payout_runs_period
        CHECK (period_end > period_start)
);

CREATE INDEX idx_payout_runs_status ON payout_runs (status);
CREATE INDEX idx_payout_runs_created_by ON payout_runs (created_by);
CREATE INDEX idx_payout_runs_period ON payout_runs (period_start, period_end);

CREATE TABLE payout_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payout_run_id BIGINT NOT NULL,
    cafe_id BIGINT NOT NULL,
    redemption_count INTEGER NOT NULL,
    credits_redeemed INTEGER NOT NULL,
    amount_owed NUMERIC(12,2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_payout_lines_payout_run
        FOREIGN KEY (payout_run_id) REFERENCES payout_runs (id),
    CONSTRAINT fk_payout_lines_cafe
        FOREIGN KEY (cafe_id) REFERENCES cafes (id),
    CONSTRAINT uq_payout_lines_run_cafe
        UNIQUE (payout_run_id, cafe_id),
    CONSTRAINT chk_payout_lines_redemption_count
        CHECK (redemption_count >= 0),
    CONSTRAINT chk_payout_lines_credits_redeemed
        CHECK (credits_redeemed >= 0),
    CONSTRAINT chk_payout_lines_amount_owed
        CHECK (amount_owed >= 0)
);

CREATE INDEX idx_payout_lines_cafe_id ON payout_lines (cafe_id);

CREATE TABLE cafe_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payout_line_id BIGINT NOT NULL,
    cafe_id BIGINT NOT NULL,
    amount NUMERIC(12,2) NOT NULL,
    payment_date DATE NOT NULL,
    reference VARCHAR(255),
    recorded_by BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cafe_payments_payout_line
        FOREIGN KEY (payout_line_id) REFERENCES payout_lines (id),
    CONSTRAINT fk_cafe_payments_cafe
        FOREIGN KEY (cafe_id) REFERENCES cafes (id),
    CONSTRAINT fk_cafe_payments_recorded_by
        FOREIGN KEY (recorded_by) REFERENCES users (id),
    CONSTRAINT chk_cafe_payments_amount
        CHECK (amount > 0)
);

CREATE INDEX idx_cafe_payments_payout_line_id ON cafe_payments (payout_line_id);
CREATE INDEX idx_cafe_payments_cafe_id ON cafe_payments (cafe_id);
CREATE INDEX idx_cafe_payments_recorded_by ON cafe_payments (recorded_by);
CREATE INDEX idx_cafe_payments_payment_date ON cafe_payments (payment_date);

CREATE TABLE admin_audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_user_id BIGINT NOT NULL,
    action VARCHAR(100) NOT NULL,
    entity_type VARCHAR(100) NOT NULL,
    entity_id BIGINT,
    details TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_admin_audit_events_admin_user
        FOREIGN KEY (admin_user_id) REFERENCES users (id)
);

CREATE INDEX idx_admin_audit_events_admin_user_id
    ON admin_audit_events (admin_user_id);
CREATE INDEX idx_admin_audit_events_entity
    ON admin_audit_events (entity_type, entity_id);
CREATE INDEX idx_admin_audit_events_created_at
    ON admin_audit_events (created_at);
